@startuml

package presentation {
    +class Main {
        +{static}main(args: String[]): void
    }

    +class MainScreenView {

    }

    +class MainScreenController {
    }
    
}

package domain {
}

package datasource {
}

MainScreenView ..> Main

@enduml